# Site settings
author: James Savory
title: Data Science Technical Blog
header-img: img/home-bg.png
email: james.pa.savory@gmail.com
copyright_name: James Savory
description: > # this means to ignore newlines until "baseurl:"
  Written for Other Aspiring Data Scientists
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jsavory-94

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
